const BlogData = [
  {
    id: 1,
    category: "Agreements",
    title: "Easy ways to implement wellbeing programs",
    date: "MAY 17, 2022",
    comments: 3,
    imageSrc: "images/coworking/blog/blog-01.jpg",
  },
  {
    id: 2,
    category: "coworking",
    title: "Things Can Help Any coworking Flourish Again",
    date: "APR 25, 2022",
    comments: 3,
    imageSrc: "images/coworking/blog/blog-02.jpg",
  },
  {
    id: 3,
    category: "Leadership",
    title: "Five Ways Elevate Your Employees Workplace",
    date: "APR 08, 2022",
    comments: 3,
    imageSrc: "images/coworking/blog/blog-03.jpg",
  },
  {
    id: 4,
    category: "Marketing",
    title: "Find Your Target Market for coworking Spaces",
    date: "JUN 03, 2020",
    comments: 3,
    imageSrc: "images/coworking/blog/blog-04.jpg",
  },
  {
    id: 5,
    category: "Proptech",
    title: "Lead Generation and Your coworking Marketing Strategy",
    date: "JUN 03, 2020",
    comments: 3,
    imageSrc: "images/coworking/blog/blog-05.jpg",
  },
  {
    id: 6,
    category: "Strategies",
    title: "Creating A Marketing Plan For Your coworking Space",
    date: "MAY 26, 2020",
    comments: 3,
    imageSrc: "images/coworking/blog/blog-06.jpg",
  },
  {
    id: 7,
    category: "Agreements",
    title: "Global IT consulting & software solutions provider",
    date: "MAY 26, 2020",
    comments: 3,
    imageSrc: "images/coworking/blog/blog-07.jpg",
  },
  {
    id: 8,
    category: "coworking",
    title: "Premium custom office solution solves Growfusely’s growing",
    date: "JUN 29, 2019",
    comments: 3,
    imageSrc: "images/coworking/blog/blog-08.jpg",
  },
  {
    id: 9,
    category: "Marketing",
    title: "Find Your Target Market for coworking Spaces",
    date: "JUN 03, 2020",
    comments: 3,
    imageSrc: "images/coworking/blog/blog-04.jpg",
  },
];

export default BlogData;
