const ServiceData = [
  {
    id: 1,
    imageSrc: "images/coworking/services/service-01.jpg",
    category: "Corporate",
    title: "People Management",
    link: "#",
    iconClass: "pbmit-xido-icon-website",
  },
  {
    id: 2,
    imageSrc: "images/coworking/services/service-02.jpg",
    category: "coworking",
    title: "Growth Strategy",
    link: "#",
    iconClass: "pbmit-xido-icon-investment",
  },
  {
    id: 3,
    imageSrc: "images/coworking/services/service-03.jpg",
    category: "Leadership",
    title: "Systems Maintenance",
    link: "#",
    iconClass: "pbmit-xido-icon-financial-consultant",
  },
  {
    id: 4,
    imageSrc: "images/coworking/services/service-04.jpg",
    category: "Lifestyle",
    title: "Innovativeness",
    link: "#",
    iconClass: "pbmit-xido-icon-atm-machine",
  },
  {
    id: 5,
    imageSrc: "images/coworking/services/service-05.jpg",
    category: "Marketing",
    title: "Admin Department",
    link: "#",
    iconClass: "pbmit-xido-icon-team",
  },
  {
    id: 6,
    imageSrc: "images/coworking/services/service-06.jpg",
    category: "Strategies",
    title: "Works Progress",
    link: "#",
    iconClass: "pbmit-xido-icon-rating",
  },
  {
    id: 7,
    imageSrc: "images/coworking/services/service-07.jpg",
    category: "Corporate",
    title: "coworking Spaces",
    link: "#",
    iconClass: "pbmit-xido-icon-statistics",
  },
  {
    id: 8,
    imageSrc: "images/coworking/services/service-08.jpg",
    category: "Leadership",
    title: "Global Movement",
    link: "#",
    iconClass: "pbmit-xido-icon-seo",
  },
  {
    id: 9,
    imageSrc: "images/coworking/services/service-09.jpg",
    category: "Marketing",
    title: "Work Alternatives",
    link: "#",
    iconClass: "pbmit-xido-icon-online-marketing-1",
  },
];

export default ServiceData;
